

/*
 * A place must have the following fields:
 * - name
 * - slug
 * - city
 * - state
 * - created at 
 * - updated at
 */


create table Place (
    id int8 NOT NULL GENERATED by default AS IDENTITY,
    city varchar(255), 
    created_at timestamp, 
    name varchar(255), 
    slug varchar(255), 
    state varchar(255), 
    updated_at timestamp, 
    primary key (id)
);

alter table Place add column createdAt timestamp;
alter table Place add column updatedAt timestamp;