

/*
 * A place must have the following fields:
 * - name
 * - slug
 * - city
 * - state
 * - created at 
 * - updated at
 */
DROP TABLE IF EXISTS Place;
CREATE TABLE Place (
    id int8 NOT NULL GENERATED by default AS IDENTITY,
    name varchar(255) NOT NULL,
    slug varchar(255) NOT NULL,
    city varchar(255) NOT NULL,
    state varchar(255) NOT NULL,
    created_at timestamp NOT NULL,
    updated_at timestamp NOT NULL,
    PRIMARY KEY (id)
);
alter table Place add column createdAt timestamp;
alter table Place add column updatedAt timestamp;